# Generated by Django 4.0.5 on 2022-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prevOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=[]),
        ),
    ]
